### ISSUE TITLE
question

### ISSUE THREAD

**Issue by KalElSuper** [fernandodelacalle/MI_Feature_Selection_ICIP_2013#1]
function [ im ] = imcal(f,l)
    cd('MutualInformationICA/');
    im = MIxnyn(f,l);
    cd('..');
end

Please ask, what does this method mean? The operation was reported incorrectly.

**Comment by fernandodelacalle** [comment]
You need to install the MIxnyn function. It was available in http://www.klab.caltech.edu/~kraskov/MILCA/ but now seems lost.
